[workspace]
members = [
    "dasp",
    "dasp_envelope",
    "dasp_frame",
    "dasp_interpolate",
    "dasp_peak",
    "dasp_ring_buffer",
    "dasp_rms",
    "dasp_sample",
    "dasp_signal",
    "dasp_slice",
    "dasp_window",
    "examples",
]
